version: '3.8'

services:
  app:
    build: .
    container_name: ecomus-api-service
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  # Optional: persistent storage for local assets if needed
  uploads:
